/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_Utils_JniString */

#ifndef _Included_com_example_hellojni_Utils_JniString
#define _Included_com_example_hellojni_Utils_JniString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_Utils_JniString
 * Method:    helloJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_Utils_JniString_helloJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
